#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 sushi Izawa
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0 
ans_s = 1

for line in sys.stdin:
    try:
        ans += int(line)
        ans_s *= int(line)
        
    except:
        ans += float(line)
        ans_s *= float(line)

print(" Sum:", ans, ",Multiplication:", ans_s)



